### ISSUE TITLE
Will you share the processed datasets, like ModelNet10 ModelNet40?

### ISSUE THREAD

**Issue by zshyang** [VimsLab/MeshNet2#2]

**Comment by sheshap** [comment]
Please check https://github.com/VimsLab/DMC

**Comment by zshyang** [comment]
Thanks!

**Comment by vinitveersingh** [comment]
That link does not have the ModelNet10 dataset. Please find the link to the ModelNet40 and ModelNet10 datasets [here](https://drive.google.com/drive/folders/1eMTg6VW3F0wHfeHvnjJuvFBxHITPvcwp?usp=sharing). Please close the issue if you can download and run the code.

**Comment by zshyang** [comment]
solved. thanks.
